version: '3.4'

services:
  redis:
    image: "redis"
    hostname: session_store
    container_name: session_store
    command: redis-server --requirepass password
    restart: unless-stopped
    ports:
      - "6379:6379"
    network_mode: redis_bridge